name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Install dependencies
        run: pnpm install
      - name: Install firebase
        run: curl -sL https://firebase.tools | bash
      - name: Login to firebase
        run: echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | base64 --decode > credentials.json
      - name: Install stripe
        run: |
          curl -s https://packages.stripe.dev/api/security/keypair/stripe-cli-gpg/public | gpg --dearmor | sudo tee /usr/share/keyrings/stripe.gpg
          echo "deb [signed-by=/usr/share/keyrings/stripe.gpg] https://packages.stripe.dev/stripe-cli-debian-local stable main" | sudo tee -a /etc/apt/sources.list.d/stripe.list
          sudo apt-get update
          sudo apt-get install -y stripe
      - name: Start dev server
        run: pnpm run dev &
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "credentials.json"
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      - name: Wait for server to start
        run: sleep 5
      - name: Cypress run
        run: pnpm run test
        env:
          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VINTEDBOT_3F0D6 }}
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore #
