name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Start dev server
        run: pnpm run dev &
      - name: Wait for dev server to start
        run: sleep 5
      - name: Set credentials
        run: echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VINTEDBOT_3F0D6 }} > credentials.json && export GOOGLE_APPLICATION_CREDENTIALS=credentials.json
      - name: Cypress run
        uses: cypress-io/github-action@v5
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
